create or replace
PROCEDURE POPULATE_TITLES_OF_INVOICE
(
  P_INVOICE_NO IN VARCHAR2,
  P_BOOKFAIR_ID IN INTEGER
) AS 
  V_TITLE TITLES%ROWTYPE;
  V_TITLE_ID INTEGER;
  V_TITLE_CNT INTEGER;
BEGIN
  FOR REC IN (
    SELECT A.ISBN, TITLE, PUBLISHER, AUTHOR,
      GROSSAMT, CURRENCY, CONV_RATE, NETAMT, DISCOUNT
    FROM TITLERECEIPTS A, INVOICES B
    WHERE 
    A.INVOICE_NO = B.INVOICE_NO
    AND A.ISBN = B.ISBN
    AND A.INVOICE_NO = P_INVOICE_NO
  )
  LOOP
    SELECT COUNT(ID) INTO V_TITLE_CNT FROM TITLES 
      WHERE BOOKFAIR_ID = P_BOOKFAIR_ID
      AND ISBN = REC.ISBN;
    IF V_TITLE_CNT > 0 THEN
      UPDATE TITLES SET COPIES_CNT = NVL(COPIES_CNT,0) + 1 
        WHERE BOOKFAIR_ID = P_BOOKFAIR_ID
        AND ISBN = REC.ISBN;
    ELSE
      SELECT TITLES_SEQ.NEXTVAL INTO V_TITLE_ID
        FROM DUAL;
      
      V_TITLE := NULL;
      V_TITLE.ID := V_TITLE_ID;
      V_TITLE.ISBN := REC.ISBN;
      V_TITLE.TITLE := REC.TITLE;
      V_TITLE.PUBLISHER := REC.PUBLISHER;
      V_TITLE.AUTHOR := REC.AUTHOR;
      V_TITLE.GROSSAMT := REC.GROSSAMT;
      V_TITLE.CURRENCY := REC.CURRENCY;
      V_TITLE.CONV_RATE := REC.CONV_RATE;
      V_TITLE.DISCOUNT := REC.DISCOUNT;
      V_TITLE.NETAMT := REC.NETAMT;
      V_TITLE.BOOKFAIR_ID := P_BOOKFAIR_ID;
      V_TITLE.COPIES_CNT := 1;
      V_TITLE.SOLD_CNT := 0;
      V_TITLE.CREATED_BY := NULL;
      V_TITLE.MODIFIED_BY := NULL;
      V_TITLE.CREATED_AT := SYSDATE;
      V_TITLE.UPDATED_AT := SYSDATE;
      
      INSERT INTO TITLES
      VALUES V_TITLE;
    END IF;
  END LOOP;
END POPULATE_TITLES_OF_INVOICE;