require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BillitemsController do

  def mock_billitem(stubs={})
    @mock_billitem ||= mock_model(Billitem, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all billitems as @billitems" do
      Billitem.stub(:all) { [mock_billitem] }
      get :index
      assigns(:billitems).should eq([mock_billitem])
    end
  end

  describe "GET show" do
    it "assigns the requested billitem as @billitem" do
      Billitem.stub(:find).with("37") { mock_billitem }
      get :show, :id => "37"
      assigns(:billitem).should be(mock_billitem)
    end
  end

  describe "GET new" do
    it "assigns a new billitem as @billitem" do
      Billitem.stub(:new) { mock_billitem }
      get :new
      assigns(:billitem).should be(mock_billitem)
    end
  end

  describe "GET edit" do
    it "assigns the requested billitem as @billitem" do
      Billitem.stub(:find).with("37") { mock_billitem }
      get :edit, :id => "37"
      assigns(:billitem).should be(mock_billitem)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created billitem as @billitem" do
        Billitem.stub(:new).with({'these' => 'params'}) { mock_billitem(:save => true) }
        post :create, :billitem => {'these' => 'params'}
        assigns(:billitem).should be(mock_billitem)
      end

      it "redirects to the created billitem" do
        Billitem.stub(:new) { mock_billitem(:save => true) }
        post :create, :billitem => {}
        response.should redirect_to(billitem_url(mock_billitem))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved billitem as @billitem" do
        Billitem.stub(:new).with({'these' => 'params'}) { mock_billitem(:save => false) }
        post :create, :billitem => {'these' => 'params'}
        assigns(:billitem).should be(mock_billitem)
      end

      it "re-renders the 'new' template" do
        Billitem.stub(:new) { mock_billitem(:save => false) }
        post :create, :billitem => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested billitem" do
        Billitem.stub(:find).with("37") { mock_billitem }
        mock_billitem.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :billitem => {'these' => 'params'}
      end

      it "assigns the requested billitem as @billitem" do
        Billitem.stub(:find) { mock_billitem(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:billitem).should be(mock_billitem)
      end

      it "redirects to the billitem" do
        Billitem.stub(:find) { mock_billitem(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(billitem_url(mock_billitem))
      end
    end

    describe "with invalid params" do
      it "assigns the billitem as @billitem" do
        Billitem.stub(:find) { mock_billitem(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:billitem).should be(mock_billitem)
      end

      it "re-renders the 'edit' template" do
        Billitem.stub(:find) { mock_billitem(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested billitem" do
      Billitem.stub(:find).with("37") { mock_billitem }
      mock_billitem.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the billitems list" do
      Billitem.stub(:find) { mock_billitem }
      delete :destroy, :id => "1"
      response.should redirect_to(billitems_url)
    end
  end

end
