require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BookfairsController do

  def mock_bookfair(stubs={})
    @mock_bookfair ||= mock_model(Bookfair, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all bookfairs as @bookfairs" do
      Bookfair.stub(:all) { [mock_bookfair] }
      get :index
      assigns(:bookfairs).should eq([mock_bookfair])
    end
  end

  describe "GET show" do
    it "assigns the requested bookfair as @bookfair" do
      Bookfair.stub(:find).with("37") { mock_bookfair }
      get :show, :id => "37"
      assigns(:bookfair).should be(mock_bookfair)
    end
  end

  describe "GET new" do
    it "assigns a new bookfair as @bookfair" do
      Bookfair.stub(:new) { mock_bookfair }
      get :new
      assigns(:bookfair).should be(mock_bookfair)
    end
  end

  describe "GET edit" do
    it "assigns the requested bookfair as @bookfair" do
      Bookfair.stub(:find).with("37") { mock_bookfair }
      get :edit, :id => "37"
      assigns(:bookfair).should be(mock_bookfair)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created bookfair as @bookfair" do
        Bookfair.stub(:new).with({'these' => 'params'}) { mock_bookfair(:save => true) }
        post :create, :bookfair => {'these' => 'params'}
        assigns(:bookfair).should be(mock_bookfair)
      end

      it "redirects to the created bookfair" do
        Bookfair.stub(:new) { mock_bookfair(:save => true) }
        post :create, :bookfair => {}
        response.should redirect_to(bookfair_url(mock_bookfair))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bookfair as @bookfair" do
        Bookfair.stub(:new).with({'these' => 'params'}) { mock_bookfair(:save => false) }
        post :create, :bookfair => {'these' => 'params'}
        assigns(:bookfair).should be(mock_bookfair)
      end

      it "re-renders the 'new' template" do
        Bookfair.stub(:new) { mock_bookfair(:save => false) }
        post :create, :bookfair => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bookfair" do
        Bookfair.stub(:find).with("37") { mock_bookfair }
        mock_bookfair.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :bookfair => {'these' => 'params'}
      end

      it "assigns the requested bookfair as @bookfair" do
        Bookfair.stub(:find) { mock_bookfair(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:bookfair).should be(mock_bookfair)
      end

      it "redirects to the bookfair" do
        Bookfair.stub(:find) { mock_bookfair(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(bookfair_url(mock_bookfair))
      end
    end

    describe "with invalid params" do
      it "assigns the bookfair as @bookfair" do
        Bookfair.stub(:find) { mock_bookfair(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:bookfair).should be(mock_bookfair)
      end

      it "re-renders the 'edit' template" do
        Bookfair.stub(:find) { mock_bookfair(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bookfair" do
      Bookfair.stub(:find).with("37") { mock_bookfair }
      mock_bookfair.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the bookfairs list" do
      Bookfair.stub(:find) { mock_bookfair }
      delete :destroy, :id => "1"
      response.should redirect_to(bookfairs_url)
    end
  end

end
