require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TitlesController do

  def mock_title(stubs={})
    @mock_title ||= mock_model(Title, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all titles as @titles" do
      Title.stub(:all) { [mock_title] }
      get :index
      assigns(:titles).should eq([mock_title])
    end
  end

  describe "GET show" do
    it "assigns the requested title as @title" do
      Title.stub(:find).with("37") { mock_title }
      get :show, :id => "37"
      assigns(:title).should be(mock_title)
    end
  end

  describe "GET new" do
    it "assigns a new title as @title" do
      Title.stub(:new) { mock_title }
      get :new
      assigns(:title).should be(mock_title)
    end
  end

  describe "GET edit" do
    it "assigns the requested title as @title" do
      Title.stub(:find).with("37") { mock_title }
      get :edit, :id => "37"
      assigns(:title).should be(mock_title)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created title as @title" do
        Title.stub(:new).with({'these' => 'params'}) { mock_title(:save => true) }
        post :create, :title => {'these' => 'params'}
        assigns(:title).should be(mock_title)
      end

      it "redirects to the created title" do
        Title.stub(:new) { mock_title(:save => true) }
        post :create, :title => {}
        response.should redirect_to(title_url(mock_title))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved title as @title" do
        Title.stub(:new).with({'these' => 'params'}) { mock_title(:save => false) }
        post :create, :title => {'these' => 'params'}
        assigns(:title).should be(mock_title)
      end

      it "re-renders the 'new' template" do
        Title.stub(:new) { mock_title(:save => false) }
        post :create, :title => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested title" do
        Title.stub(:find).with("37") { mock_title }
        mock_title.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :title => {'these' => 'params'}
      end

      it "assigns the requested title as @title" do
        Title.stub(:find) { mock_title(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:title).should be(mock_title)
      end

      it "redirects to the title" do
        Title.stub(:find) { mock_title(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(title_url(mock_title))
      end
    end

    describe "with invalid params" do
      it "assigns the title as @title" do
        Title.stub(:find) { mock_title(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:title).should be(mock_title)
      end

      it "re-renders the 'edit' template" do
        Title.stub(:find) { mock_title(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested title" do
      Title.stub(:find).with("37") { mock_title }
      mock_title.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the titles list" do
      Title.stub(:find) { mock_title }
      delete :destroy, :id => "1"
      response.should redirect_to(titles_url)
    end
  end

end
